### ISSUE TITLE
promts to enter passphrase

### ISSUE THREAD

**Issue by websensei** [seanchann/sshlogin#1]
ssh -i /home/user/.ssh/id_rsa.pub core@dock.server.com -p22
Enter passphrase for key '/home/user/.ssh/id_rsa.pub':

My configuration:
  "default": [
                                                {
                                                        "name": "CoreOS",
                                                        "user": "core",
                                                        "host": "dock.server.com",
                                                        "port": 22,
                                                        "pubkeyfile": "/home/user/.ssh/id_rsa.pub"
                                                }
                                        ]

my ssh key doesn't have passphrase. from the the terminal works fine, but with your plugin not.

**Comment by seanchann** [comment]
open a terminal  on vscode.  connect remote server by command line in this terminal. test it! thanks.

**Comment by websensei** [comment]
The output when I try to login with your plugin to my remote server with key (passwordless):

ssh -i /home/user/.ssh/id_rsa.pub core@dock.server.com -p 22
 user  ssh -i /home/user/.ssh/id_rsa.pub core@dock.server.com -p 22
Enter passphrase for key '/home/user/.ssh/id_rsa.pub':
Password:

[1]+  Stopped                 ssh -i /home/user/.ssh/id_rsa.pub core@dock.server.com -p 22

then in the same terminal I try login as usually:

 user  ssh core@dock.server.com
Last login: Sat Aug 19 12:22:55 UTC 2017 from 5.199.xxx.x on pts/0
Container Linux by CoreOS stable (1409.9.0)
core@dock ~ $

**Comment by seanchann** [comment]
okay,  I will test it on coreos.

**Comment by websensei** [comment]
my workhorse has a latest Centos 7, and remote host is stable CoreOS

**Comment by tlongren** [comment]
`ssh -i` should be followed by a path to the private key, not public key. Will send a pull request soon that fixes this.

**Comment by tlongren** [comment]
public keys don't have a passphrase. Private keys do.

Public vs private keys were confused here. I fixed this with #2.

**Comment by seanchann** [comment]
thanks tlongren, I made a mistake
